[agent.planner]
model = "gpt-4"
reasoning_level = "medium"

[agent.worker]
model = "gpt-4"
reasoning_level = "medium"

[core.implementation]
task_store_backend = "copilot_team.tasks.SqliteTaskStoreBackend"

[core.workdir]
location = "./workdir"

[core.workdir.repositories]
charsetrs = "https://github.com/mariotaddeucci/charsetrs.git"
